admins: []
forwards:
- dest:
  - -1001306188161
  end: null
  offset: 15170
  source: -1001331006379
live:
  delete_on_edit: null
  delete_sync: false
past:
  delay: 0.0
plugins:
  filter:
    files:
      whitelist:
      - audio
      - video
      - document
      - photo
show_forwarded_from: false
