admins: []
forwards:
- source:  -1001493034047
  dest:
  - -1001583349964
  offset: 0
  end: null
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 0.0
plugins:
  filter:
    files:
      whitelist:
      - audio
      - video
      - document
      - photo
